Feature/login
PedroVegaDamian/Orimi pull request #5
Opened 2024-04-18 21:59 UTC by rocio-peralta

2024-04-18 22:19 UTC, PedroVegaDamian requested changes

2024-04-18 22:19 UTC, PedroVegaDamian commented on src/pages/Login.tsx
> +import { auth } from '../firebase'
utilzar @ para los imports
```suggestion
import { auth } from '@/firebase'
```

2024-04-18 22:19 UTC, PedroVegaDamian commented on src/pages/Login.tsx
> +export const Login = () => {
utilizar LoginPage como nombre del componente

2024-04-18 22:19 UTC, PedroVegaDamian commented on src/pages/Login.tsx
> +  function goTo(link: string) {
se podría utilizar simplemente el `navigate(link)` directamente, no se necesitaría una función como goTo

2024-04-18 22:19 UTC, PedroVegaDamian commented on src/pages/Login.tsx
> +  const signIn = async () => {
separar funcionalidad de signInWithEmailAndPassword en un servicio

2024-04-18 22:19 UTC, PedroVegaDamian commented on src/pages/Login.tsx
> +  function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
separar la lógica en un hook, podría ser useLogin

2024-04-19 00:15 UTC, PedroVegaDev commented on src/router/index.tsx
> +import { LoginPage } from '@/pages/LoginPage'
El nombre del archivo sería Login
```suggestion
import { LoginPage } from '@/pages/Login'
```

2024-04-19 00:21 UTC, PedroVegaDamian requested changes

2024-04-19 00:21 UTC, PedroVegaDamian commented on src/services/login.ts
> +export const signInService = async (auth: Auth, email: string, password: string) => {
```suggestion
export const signIn = async (auth: Auth, email: string, password: string) => {
```

2024-04-19 00:21 UTC, PedroVegaDamian commented on src/services/login.ts
> +      return { success: false, message: 'User is not logged in' }
se puede destructurar el user, luego se puede retornar el objeto para saber que fue todo bien
```suggestion
    const { user } = await signInWithEmailAndPassword(auth, email, password)
    return { success: true, user }
```

2024-04-19 01:03 UTC, rocio-peralta commented on src/services/login.ts
> +      return { success: false, message: 'User is not logged in' }
Buena observacion! gracias!

2024-04-19 01:21 UTC, PedroVegaDamian approved these changes

2024-04-19 01:33 UTC, merged